on:
  pull_request:
    types: [opened, reopened]
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.0"
      - name: Install dependencies
        run: npm ci
      - name: Run prettier, build extension and run tests
        run: npm run run-pretty
        run: npm test
      - name: Do NPM dep audit
        run: npm audit
      
        
